import { Navbar } from "@/components/Navbar";
import { AuthProvider } from "@/services/auth-provider";
import "@/styles/tailwind.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} h-screen flex flex-col`}>
        <AuthProvider>
          {/* @ts-expect-error Async Server Component */}
          <Navbar />
        </AuthProvider>
        <main className="flex-1">{children}</main>
      </body>
    </html>
  );
}
